# This file is generated by /var/tmp/portage/dev-python/numpy-1.10.4/work/numpy-1.10.4-python2_7/setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]

blas_info={'libraries': ['blas', 'cblas'], 'library_dirs': ['/usr/lib64/blas/reference'], 'language': 'c', 'define_macros': [('HAVE_CBLAS', None)]}
lapack_info={'libraries': ['lapack', 'blas'], 'library_dirs': ['/usr/lib64/lapack/reference', '/usr/lib64/blas/reference'], 'language': 'f77'}
lapack_opt_info={'libraries': ['lapack', 'blas', 'blas', 'cblas'], 'library_dirs': ['/usr/lib64/lapack/reference', '/usr/lib64/blas/reference'], 'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'language': 'c'}
system_info={}
blas_opt_info={'libraries': ['blas', 'cblas'], 'library_dirs': ['/usr/lib64/blas/reference'], 'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'language': 'c'}

def get_info(name):
    g = globals()
    return g.get(name, g.get(name + "_info", {}))

def show():
    for name,info_dict in globals().items():
        if name[0] == "_" or type(info_dict) is not type({}): continue
        print(name + ":")
        if not info_dict:
            print("  NOT AVAILABLE")
        for k,v in info_dict.items():
            v = str(v)
            if k == "sources" and len(v) > 200:
                v = v[:60] + " ...\n... " + v[-60:]
            print("    %s = %s" % (k,v))
    